name = "power"
name_pretty = "Power Menu"
icon = "system-shutdown"

[[entries]]
text = "Lock Screen"
icon = "system-lock-screen"
actions = { "lock" = "hyprlock" }

[[entries]]
text = "Logout Hyprland"
icon = "system-log-out"
actions = { "logout" = "uwsm stop" }

[[entries]]
text = "Suspend"
icon = "system-suspend"
actions = { "suspend" = "hyprlock & sleep 0.5; systemctl suspend" }

[[entries]]
text = "Reboot"
icon = "system-reboot"
actions = { "reboot" = "systemctl reboot" }

[[entries]]
text = "Power Off"
icon = "system-shutdown"
actions = { "poweroff" = "systemctl poweroff" }

[[entries]]
text = "Kill User Session"
icon = "application-exit"
actions = { "kill" = "loginctl kill-user $USER" }
